apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
data:
  SPRING_PROFILE_ACTIVE: {{ .Values.config.SPRING_PROFILE_ACTIVE | quote }}
  POSTGRES_DB_HOST: {{ .Values.config.POSTGRES_DB_HOST | quote }}
  POSTGRES_DB_NAME: {{ .Values.config.POSTGRES_DB_NAME | quote }}
  POSTGRES_DB_PORT: {{ .Values.config.POSTGRES_DB_PORT | quote }}
  POSTGRES_USER: {{ .Values.config.POSTGRES_USER | quote }}
  KAKAO_REDIRECT_URI: {{ .Values.config.KAKAO_REDIRECT_URI | quote }}
  KAKAO_LOGOUT_REDIRECT_URI: {{ .Values.config.KAKAO_LOGOUT_REDIRECT_URI | quote }}
