apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhineye-member
  labels:
    app: jhineye-member
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jhineye-member
  template:
    metadata:
      labels:
        app: jhineye-member
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: member
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: jhineye-member-config
            - secretRef:
                name: jhineye-member-secret
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
