apiVersion: v1
kind: Secret
metadata:
  name: member-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey }}
  KAKAO_CLIENT_ID: {{ .Values.secrets.kakaoClientId }}
  KAKAO_CLIENT_SECRET: {{ .Values.secrets.kakaoClientSecret }}
