server:
  port: 8765

spring:
  datasource:
    driver-class-name: org.postgresql.Driver # PostgreSQL JDBC ????? ?????.
    url: jdbc:postgresql://localhost:5432/notice_hub # ?????? ?? 'shop' ??????? ???? ?? JDBC URL???.
    platform: postgres # ???? ?????? ???? ?????.
    username: postgres # ?????? ??? ?? ??? ?????.
    password: qwer1234 # ?????? ??? ?? ???????.
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false  # Open-Session-In-View ??? ??????, ? ??? ???? ?? ?? ??? ?????.
    properties:
      hibernate:
        show_sql: true  # Hibernate? ???? SQL? ??? ?????.
        default_batch_fetch_size: 100  # ?? ?? ???? 100?? ?????. ? ?? ??? ?? ???? ?????.
        dialect: org.hibernate.dialect.PostgreSQLDialect  # ?????? ??
        format_sql: true  # SQL ??? ?? ?? ????? ?????.
        use_sql_comments: true  # SQL ??? ??? ??????.
  servlet:
    multipart:
      enabled: true  # ????(?? ??? ?) ??? ??????.
      max-file-size: 100MB  # ?? ?? ??? 100MB? ?????.
      max-request-size: 100MB  # ?? ?? ??? 100MB? ?????.
kakao:
  host-name: KAKAO
  client-id: 6bb73a683ffd93e3ebf9512656e9267c
  client-secret: eIGeH8BixyT9jpc08KrhVms2jjH6nQBI
  redirect-uri: http://localhost:8765/api/kakao/callback

jwt:
  secret-key: tempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkeytempsecretkey
  access-token-expiration-time: 900000 #60*15*1000
  refresh-token-expiration-time: 259200000 #60*60*24*3*1000