server:
  port: 8765

spring:
  datasource:
    driver-class-name: org.postgresql.Driver # PostgreSQL JDBC ????? ?????.
    url: jdbc:postgresql://localhost:5432/test # ?????? ?? 'shop' ??????? ???? ?? JDBC URL???.
    platform: postgres # ???? ?????? ???? ?????.
    username: yanoos # ?????? ??? ?? ??? ?????.
    password: yanoos # ?????? ??? ?? ???????.
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false  # Open-Session-In-View ??? ??????, ? ??? ???? ?? ?? ??? ?????.
    properties:
      hibernate:
        show_sql: true  # Hibernate? ???? SQL? ??? ?????.
        default_batch_fetch_size: 100  # ?? ?? ???? 100?? ?????. ? ?? ??? ?? ???? ?????.
        dialect: org.hibernate.dialect.PostgreSQLDialect  # ?????? ??
        format_sql: true  # SQL ??? ?? ?? ????? ?????.
        use_sql_comments: true  # SQL ??? ??? ??????.
  servlet:
    multipart:
      enabled: true  # ????(?? ??? ?) ??? ??????.
      max-file-size: 100MB  # ?? ?? ??? 100MB? ?????.
      max-request-size: 100MB  # ?? ?? ??? 100MB? ?????.
kakao:
  host-name: ${KAKAO_HOST_NAME}
  client-id: ${KAKAO_API_KEY}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-time: 900000 #60*15*1000
  refresh-token-expiration-time: 259200000 #60*60*24*3*1000