server:
  port: 8765

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    platform: postgres
    username: yanoos
    password: yanoos
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
kakao:
  host-name: KAKAO
  client-id: 6bb73a683ffd93e3ebf9512656e9267c
  client-secret: eIGeH8BixyT9jpc08KrhVms2jjH6nQBI
  redirect-uri: http://localhost:8765/kakao/callback

jwt:
  secret-key: temp-secret-key