name: Deploy Member to EKS

on:
  push:
    tags:
      - 'member-v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-northeast-2 --name jhin-eye

      - name: Deploy member via Helm
        run: |
          helm upgrade --install member ./member \
            --namespace jhin-eye \
            --create-namespace \
            -f member/values.yaml \
            --set secrets.postgresPassword=${{ secrets.POSTGRES_PASSWORD }} \
            --set secrets.jwtSecretKey=${{ secrets.JWT_SECRET_KEY }} \
            --set secrets.kakaoClientId=${{ secrets.KAKAO_CLIENT_ID }} \
            --set secrets.kakaoClientSecret=${{ secrets.KAKAO_CLIENT_SECRET }}
